/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * accueil.java
 *
 * Created on 26 févr. 2014, 15:39:19
 */

package graphique;


import java.io.IOException;
import java.sql.*;

import javax.swing.* ;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Date.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author kalb
 */
public class accueil extends javax.swing.JFrame {
    ResultSet rs , rs2,rs3,rs4 ;
Connection conn=connexion_bd.connexion(); ;
    /** Creates new form accueil */
    public accueil() {
        initComponents();
        this.setTitle("Page d'Accueuill");
        tache();
         formation();
       conn=connexion_bd.connexion();

    }
    private void formation()
{
    DefaultListModel m=new  DefaultListModel();
    Calendar cal=new GregorianCalendar() ;

  m.addElement("");
  m.addElement("");

  try{

int Y=cal.get(Calendar.YEAR);
  int M=cal.get(Calendar.MONTH);
  int d=cal.get(Calendar.DAY_OF_MONTH);
  String datecurrent=Y+"-"+(M+1)+"-"+d ;

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from formation_co where date_fin> '"+datecurrent+"' ");
                        PreparedStatement pstmt2 = conn.prepareStatement("select * from formation_ct where date_fin> '"+datecurrent+"'  ");

          rs = pstmt1.executeQuery();
          rs2 = pstmt2.executeQuery();
          int n=0;  int j=0;
          while(rs.next())
          {
              String formation=rs.getString("nom_formation");
              String nive=rs.getString("niveau");
              n=n+1;
              PreparedStatement pstmt3 = conn.prepareStatement("select * from inscription where formation='"+formation+"' and niveau='"+nive+"' and type_formation='FCO' ");
              rs3=pstmt3.executeQuery();
              int i=0;
              while(rs3.next())
              {
                  i=i+1;
              }
              m.addElement("FCO:"+""+nive+"  "+":"+formation+"  "+i+" inscription");


          }
           while(rs2.next())
          {
              String FORM=rs2.getString("nom_formation");
              String niv=rs2.getString("niveau");
              j=j+1;
            PreparedStatement pstmt4 = conn.prepareStatement("select * from inscription where formation='"+FORM+"' and niveau='"+niv+"' and type_formation='FCT' ");
              rs4=pstmt4.executeQuery();
              int i=0;
              while(rs4.next())
              {
                  i=i+1;
              }
              m.addElement("FCT:"+""+niv+"  "+":"+FORM+"  "+i+" inscription");



          }
          PreparedStatement pstmt3 = conn.prepareStatement("select * from inscription  ");
              rs3=pstmt3.executeQuery();
              int i=0;
              while(rs3.next())
              {
                  i=i+1;
              }
               m.addElement("nombre de formation Continue     :"+ "   "+n+" ");
               m.addElement("nombre formation à court terme  :"+ "   "+j+" ");
              m.addElement("total d'inscription aux formations:"+ "  "+i+" ");
jList2.setModel(m);






	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}


}

private void tache()
{
    DefaultListModel m=new  DefaultListModel();
  Calendar cal=new GregorianCalendar() ;
  m.addElement("");
  m.addElement("");
  
  try{  
      int Y=cal.get(Calendar.YEAR);
  int M=cal.get(Calendar.MONTH);
  int d=cal.get(Calendar.DAY_OF_MONTH);
  String datecurrent=Y+"-"+(M+1)+"-"+d ;
  
   


	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from tache where date='"+datecurrent+"'  ");

          rs = pstmt1.executeQuery();
          while(rs.next())
          {
              String tach=rs.getString("tache");
              String heur=rs.getString("heure");
              int nbheur=rs.getInt("nb_heures");
              m.addElement("tache:"+""+tach+"  "+"à:"+heur+"  "+"durée:"+nbheur+"heures");
             
            
          }
jList1.setModel(m);






	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}

  
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deconnex = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        projetbtn = new javax.swing.JButton();
        groupebtn = new javax.swing.JButton();
        inscribtn = new javax.swing.JButton();
        notebtn = new javax.swing.JButton();
        parametresbtn = new javax.swing.JButton();
        clientbtn = new javax.swing.JButton();
        caissebtn = new javax.swing.JButton();
        formateurbtn = new javax.swing.JButton();
        aidebtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(1450, 740));
        setName("accueil"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(null);

        deconnex.setBackground(new java.awt.Color(102, 0, 51));
        deconnex.setForeground(new java.awt.Color(255, 255, 255));
        deconnex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/deconnexion.jpg"))); // NOI18N
        deconnex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deconnexMouseClicked(evt);
            }
        });
        getContentPane().add(deconnex);
        deconnex.setBounds(900, 510, 150, 150);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/formation.jpg"))); // NOI18N
        jButton5.setMaximumSize(new java.awt.Dimension(200, 100));
        jButton5.setMinimumSize(new java.awt.Dimension(200, 100));
        jButton5.setPreferredSize(new java.awt.Dimension(200, 100));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(150, 60, 150, 150);

        projetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/proj.jpg"))); // NOI18N
        projetbtn.setPreferredSize(new java.awt.Dimension(113, 89));
        projetbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetbtnMouseClicked(evt);
            }
        });
        projetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projetbtnActionPerformed(evt);
            }
        });
        getContentPane().add(projetbtn);
        projetbtn.setBounds(300, 60, 150, 150);

        groupebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/groupe.jpg"))); // NOI18N
        groupebtn.setPreferredSize(new java.awt.Dimension(113, 89));
        groupebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                groupebtnMouseClicked(evt);
            }
        });
        groupebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupebtnActionPerformed(evt);
            }
        });
        getContentPane().add(groupebtn);
        groupebtn.setBounds(450, 360, 150, 150);

        inscribtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/inscri.jpg"))); // NOI18N
        inscribtn.setPreferredSize(new java.awt.Dimension(113, 89));
        inscribtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscribtnMouseClicked(evt);
            }
        });
        inscribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscribtnActionPerformed(evt);
            }
        });
        getContentPane().add(inscribtn);
        inscribtn.setBounds(450, 510, 150, 150);

        notebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/note.jpg"))); // NOI18N
        notebtn.setPreferredSize(new java.awt.Dimension(113, 89));
        notebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notebtnMouseClicked(evt);
            }
        });
        notebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notebtnActionPerformed(evt);
            }
        });
        getContentPane().add(notebtn);
        notebtn.setBounds(600, 60, 150, 150);

        parametresbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/ppp.jpg"))); // NOI18N
        parametresbtn.setPreferredSize(new java.awt.Dimension(113, 89));
        parametresbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametresbtnActionPerformed(evt);
            }
        });
        getContentPane().add(parametresbtn);
        parametresbtn.setBounds(750, 510, 150, 150);

        clientbtn.setBackground(new java.awt.Color(102, 0, 51));
        clientbtn.setForeground(new java.awt.Color(255, 255, 255));
        clientbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/etudiant.jpg"))); // NOI18N
        clientbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientbtnMouseClicked(evt);
            }
        });
        getContentPane().add(clientbtn);
        clientbtn.setBounds(600, 210, 150, 150);

        caissebtn.setBackground(new java.awt.Color(102, 0, 51));
        caissebtn.setForeground(new java.awt.Color(255, 255, 255));
        caissebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/caisse.jpg"))); // NOI18N
        caissebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caissebtnMouseClicked(evt);
            }
        });
        getContentPane().add(caissebtn);
        caissebtn.setBounds(600, 360, 150, 150);

        formateurbtn.setBackground(new java.awt.Color(102, 0, 51));
        formateurbtn.setForeground(new java.awt.Color(255, 255, 255));
        formateurbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/for.jpg"))); // NOI18N
        formateurbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formateurbtnMouseClicked(evt);
            }
        });
        getContentPane().add(formateurbtn);
        formateurbtn.setBounds(450, 210, 150, 150);

        aidebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/AID.jpg"))); // NOI18N
        aidebtn.setPreferredSize(new java.awt.Dimension(113, 89));
        aidebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aidebtnMouseClicked(evt);
            }
        });
        aidebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aidebtnActionPerformed(evt);
            }
        });
        getContentPane().add(aidebtn);
        aidebtn.setBounds(600, 510, 150, 150);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/menu_boutton.jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 60, 150, 150);

        jList1.setBackground(new java.awt.Color(51, 0, 51));
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1 ", " ", "Item 2", " ", "Item 3", " ", "Item 4", " ", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(750, 210, 300, 300);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/testev.jpg"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(750, 60, 300, 150);

        jList2.setBackground(new java.awt.Color(0, 102, 102));
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(150, 210, 300, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logooo copie.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1400, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projetbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projetbtnActionPerformed

    private void deconnexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnexMouseClicked
        // TODO add your handling code here:
        connexion  appelfenetre=new  connexion();
        appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

        this.setVisible(false);
    }//GEN-LAST:event_deconnexMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        
        AjoutF  appelfenetre=new  AjoutF ();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

       



}//GEN-LAST:event_jButton5MouseClicked

    private void groupebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupebtnActionPerformed

    private void inscribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscribtnActionPerformed
        // TODO add your handling code here:
         inscription  appelfenetre=new inscription ();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

        
    }//GEN-LAST:event_inscribtnActionPerformed

    private void notebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notebtnActionPerformed
        // TODO add your handling code here:
         tache  appelfenetre=new tache ();
          appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;
        this.setVisible(false);

        
    }//GEN-LAST:event_notebtnActionPerformed

    private void parametresbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametresbtnActionPerformed
        // TODO add your handling code here:
         parametre  appelfenetre=new parametre ();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

       
    }//GEN-LAST:event_parametresbtnActionPerformed

    private void clientbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientbtnMouseClicked
        // TODO add your handling code here:
         Etudiant  appelfenetre=new Etudiant ();
          appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

       
    }//GEN-LAST:event_clientbtnMouseClicked

    private void caissebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caissebtnMouseClicked
        // TODO add your handling code here:
         caisse  appelfenetre=new caisse ();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

       
    }//GEN-LAST:event_caissebtnMouseClicked

    private void groupebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_groupebtnMouseClicked
        // TODO add your handling code here:
       groupe  appelfenetre=new groupe ();
          appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

        
    }//GEN-LAST:event_groupebtnMouseClicked

    private void formateurbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formateurbtnMouseClicked
        // TODO add your handling code here:
         formateur  appelfenetre=new formateur ();
          appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

       
    }//GEN-LAST:event_formateurbtnMouseClicked

    private void aidebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aidebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aidebtnActionPerformed

    private void projetbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetbtnMouseClicked
        // TODO add your handling code here:
         projets  appelfenetre=new projets ();
         appelfenetre.setExtendedState(appelfenetre.MAXIMIZED_BOTH);
        appelfenetre.setVisible(true) ;

        
       
    }//GEN-LAST:event_projetbtnMouseClicked

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
       
    }//GEN-LAST:event_jButton5MouseEntered

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseEntered

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        tache  appelfenetre=new tache ();
          appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;
this.setVisible(false);
        

     
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         matiere  appelfenetre=new matiere ();
          appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

        

    }//GEN-LAST:event_jButton1MouseClicked

    private void aidebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aidebtnMouseClicked
        // TODO add your handling code here:
        aide  appelfenetre=new  aide();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

       
    }//GEN-LAST:event_aidebtnMouseClicked

    private void notebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notebtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_notebtnMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try{
        testevaluation  appelfenetre=new   testevaluation();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;
        } catch (IOException ex) {
                    Logger.getLogger(testevaluation.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton2MouseClicked

    private void inscribtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscribtnMouseClicked
        // TODO add your handling code here:
         inscription  appelfenetre=new  inscription();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;
    }//GEN-LAST:event_inscribtnMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 accueil appelfenetre=new accueil ();
         appelfenetre.setExtendedState(appelfenetre.MAXIMIZED_BOTH);
        appelfenetre.setVisible(true) ;
               

               
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aidebtn;
    private javax.swing.JButton caissebtn;
    private javax.swing.JButton clientbtn;
    private javax.swing.JButton deconnex;
    private javax.swing.JButton formateurbtn;
    private javax.swing.JButton groupebtn;
    private javax.swing.JButton inscribtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton notebtn;
    private javax.swing.JButton parametresbtn;
    private javax.swing.JButton projetbtn;
    // End of variables declaration//GEN-END:variables

}
