/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * aide.java
 *
 * Created on 21 mars 2014, 14:20:05
 */

package graphique;



/**
 *
 * @author zied_2
 */
public class aide extends javax.swing.JFrame {
   


    /** Creates new form aide */
    public aide() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        pantala = new java.awt.Panel();
        barratiempo = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        volume = new javax.swing.JSlider();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 720));
        getContentPane().setLayout(null);

        panel1.setLayout(null);
        getContentPane().add(panel1);
        panel1.setBounds(879, 30, 290, 570);

        pantala.setBackground(new java.awt.Color(0, 0, 0));
        pantala.setLayout(null);
        getContentPane().add(pantala);
        pantala.setBounds(20, 30, 830, 500);
        getContentPane().add(barratiempo);
        barratiempo.setBounds(20, 530, 830, 23);

        jButton1.setText("play|>");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 570, 90, 30);

        jButton3.setText("||> pause");
        getContentPane().add(jButton3);
        jButton3.setBounds(120, 570, 90, 30);
        getContentPane().add(volume);
        volume.setBounds(700, 570, 150, 23);

        jButton2.setText("|| arreter");
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 570, 100, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel2.setText("Volume");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(640, 580, 50, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logooo copie.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jButton1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider barratiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Panel panel1;
    private java.awt.Panel pantala;
    private javax.swing.JSlider volume;
    // End of variables declaration//GEN-END:variables

}
