/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AjoutF.java
 *
 * Created on 29 avr. 2014, 13:58:34
 */

package graphique;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils ;

/**
 *
 * @author zied_2
 */
public class AjoutF extends javax.swing.JFrame {
Connection conn =connexion_bd.connexion();
ResultSet rs;
    /** Creates new form AjoutF */
    public AjoutF() {
        initComponents();
 conn =connexion_bd.connexion();
 update_fct();
 update_fco();
 this.setTitle("Gestionnaire de formation");
 
 
    }
  
 private void update_fct()
 {
  DefaultListModel n=new  DefaultListModel();


  try{





	    		PreparedStatement pstmt1 = conn.prepareStatement("select nom_formation from formation_ct  ");

          rs = pstmt1.executeQuery();
          while(rs.next())
          {
              String nf=rs.getString("nom_formation");

              n.addElement("FCT:"+""+nf+" ");


          }
jList1.setModel(n);






	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}



 }
 private void update_fco()
 {
  DefaultListModel m=new  DefaultListModel();


  try{





	    		PreparedStatement pstmt1 = conn.prepareStatement("select nom_formation from formation_co  ");

          rs = pstmt1.executeQuery();
          while(rs.next())
          {
              String nf=rs.getString("nom_formation");

              m.addElement("FCO:"+""+nf+" ");


          }
jList2.setModel(m);






	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}


 }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1060, 690));
        setResizable(false);
        getContentPane().setLayout(null);

        panel1.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Formation continue", "Formation court terme" }));
        panel1.add(jComboBox1);
        jComboBox1.setBounds(130, 20, 160, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/correct.png"))); // NOI18N
        jButton1.setText("Gérer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        panel1.add(jButton1);
        jButton1.setBounds(300, 20, 160, 40);

        getContentPane().add(panel1);
        panel1.setBounds(210, 30, 590, 80);

        panel2.setLayout(null);

        jScrollPane2.setViewportView(jList2);

        panel2.add(jScrollPane2);
        jScrollPane2.setBounds(30, 90, 260, 370);

        jScrollPane1.setViewportView(jList1);

        panel2.add(jScrollPane1);
        jScrollPane1.setBounds(300, 90, 260, 370);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Liste de Formation Continue");
        panel2.add(jLabel2);
        jLabel2.setBounds(40, 44, 170, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Liste de Formation Court Terme");
        panel2.add(jLabel3);
        jLabel3.setBounds(310, 44, 200, 20);

        getContentPane().add(panel2);
        panel2.setBounds(210, 130, 590, 520);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/a_p.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1090, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String ftype=jComboBox1.getSelectedItem().toString();
        if(ftype.equalsIgnoreCase("Formation continue"))
        {
             Fco appelfenetre=new  Fco ();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;

        }
        else if(ftype.equals("Formation court terme"))
        {
Fct appelfenetre=new  Fct ();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;
        }
    }//GEN-LAST:event_jButton1MouseClicked
///***************Action sur bouttons et apel du fonctions***********************

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables

}
