/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * depense.java
 *
 * Created on 23 avr. 2014, 20:51:01
 */

package graphique;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import net.proteanit.sql.DbUtils ;

/**
 *
 * @author zied_2
 */
public class depense extends javax.swing.JFrame {
    ResultSet rs;
    Connection conn=connexion_bd.connexion();

    /** Creates new form depense */
    public depense() {
        initComponents();
        ajouter();
        modifier();
       
        annuler();
        update_depense();
        this.setTitle("Gestionnaire de dépense");
        conn=connexion_bd.connexion();
    }
    private void imprime () throws IOException
    {
        try
        {
    Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\zied_2\\Documents\\NetBeansProjects\\Gesfor\\dist\\depense.pdf");
        }
    catch(Exception e)
    {
      System.out.println(e.getMessage());
    }
    }
    //code pour l'affichage de depenses creer
     private void update_depense(){
    try{

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from depenses  ");

          rs = pstmt1.executeQuery();

tdepense.setModel(DbUtils.resultSetToTableModel(rs));

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
   }
     //code pour la creation de depense
private void ajouter(){
 try{

	    		PreparedStatement pstmt1 = conn.prepareStatement("insert into depenses (libele,montant,benificiaire,date) values (?,?,?,?)");



  pstmt1.setString(1,libelee.getText());
   pstmt1.setInt(2,Integer.parseInt(montantd.getText()));
   pstmt1.setString(3,benificiaire.getText());
   pstmt1.setString(4,((JTextField)datepaie.getDateEditor().getUiComponent()).getText());
   


         int resultat = pstmt1.executeUpdate();



	    		 JOptionPane.showMessageDialog(null,"paiement enregistrer");
	    }
	    	catch(Exception c){
System.out.println(c.toString());

	    	}

    update_depense();
}
//code pour la modification de depense
private void modifier(){
 try{
              int row=tdepense.getSelectedRow();
 String ID=(tdepense.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);

String lib=libelee.getText();

String montanp=montantd.getText();
int montan=Integer.parseInt(montanp);
String datep=((JTextField)datepaie.getDateEditor().getUiComponent()).getText();
String benif=benificiaire.getText();




        PreparedStatement pstmt1 = conn.prepareStatement("update  depenses set libele='"+lib+"',montant='"+montan+"',benificiaire='"+benif+"',date='"+datep+"'  where id_depense= '"+id+"' ");




         int resultat = pstmt1.executeUpdate();


	    		 JOptionPane.showMessageDialog(null,"mise à jour effectuer");




	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
    update_depense();
}
//code pour la suppression de depense

private void annuler(){
libelee.setText("");
montantd.setText("");
        
        datepaie.setDate(null);
benificiaire.setText("");
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdepense = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        datepaie = new com.toedter.calendar.JDateChooser();
        benificiaire = new javax.swing.JTextField();
        montantd = new javax.swing.JTextField();
        libelee = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        panel1.setLayout(null);

        tdepense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tdepense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdepenseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdepense);

        panel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 40, 500, 280);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ajouter-crayon-icone-4828-32.png"))); // NOI18N
        jButton4.setText("Ajouter");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        panel1.add(jButton4);
        jButton4.setBounds(650, 40, 180, 40);

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icon_print.png"))); // NOI18N
        jButton6.setText("Imprimer");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        panel1.add(jButton6);
        jButton6.setBounds(650, 100, 180, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/kedit-icone-8843-32.png"))); // NOI18N
        jButton1.setText("modifier");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        panel1.add(jButton1);
        jButton1.setBounds(650, 160, 180, 40);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-4878-32.png"))); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2);
        jButton2.setBounds(650, 220, 180, 40);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-7248-32.png"))); // NOI18N
        jButton3.setText("Annuler");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        panel1.add(jButton3);
        jButton3.setBounds(650, 280, 180, 40);

        datepaie.setDateFormatString("yyyy-MM-dd ");
        datepaie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datepaieMouseClicked(evt);
            }
        });
        panel1.add(datepaie);
        datepaie.setBounds(650, 360, 180, 40);

        benificiaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                benificiaireMouseClicked(evt);
            }
        });
        benificiaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                benificiaireKeyTyped(evt);
            }
        });
        panel1.add(benificiaire);
        benificiaire.setBounds(440, 360, 170, 40);

        montantd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                montantdMouseClicked(evt);
            }
        });
        montantd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montantdKeyTyped(evt);
            }
        });
        panel1.add(montantd);
        montantd.setBounds(270, 360, 160, 40);

        libelee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libeleeMouseClicked(evt);
            }
        });
        libelee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                libeleeKeyTyped(evt);
            }
        });
        panel1.add(libelee);
        libelee.setBounds(110, 360, 150, 40);

        jLabel3.setText("Libelé depense:");
        panel1.add(jLabel3);
        jLabel3.setBounds(110, 334, 100, 20);

        jLabel4.setText("Montant dépense:");
        panel1.add(jLabel4);
        jLabel4.setBounds(274, 334, 110, 20);

        jLabel5.setText("Béneficiaire:");
        panel1.add(jLabel5);
        jLabel5.setBounds(440, 334, 100, 20);

        jLabel6.setText("Date:");
        panel1.add(jLabel6);
        jLabel6.setBounds(650, 334, 90, 20);

        getContentPane().add(panel1);
        panel1.setBounds(50, 160, 950, 450);

        panel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Gestionnaire De Dépenses");
        panel2.add(jLabel2);
        jLabel2.setBounds(340, 40, 300, 40);

        getContentPane().add(panel2);
        panel2.setBounds(50, 30, 950, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logooo copie.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1060, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        ajouter();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         modifier();

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
          int c=JOptionPane.showConfirmDialog(null,"tu veux supprimer"," supprime",JOptionPane.YES_NO_OPTION);
        if(c==0){
 try{
              int row=tdepense.getSelectedRow();
 String ID=(tdepense.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);



        PreparedStatement pstmt1 = conn.prepareStatement("delete  from depenses where id_depense= '"+id+"' ");




         int resultat = pstmt1.executeUpdate();


	    		 JOptionPane.showMessageDialog(null,"depense supprimer");




	    }
	    	catch(Exception e){
	    		System.out.println(e.getMessage());

	    	}}
    update_depense();

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
         annuler();
    }//GEN-LAST:event_jButton3MouseClicked

    private void libeleeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libeleeMouseClicked
        // TODO add your handling code here:
        libelee.setText("");
    }//GEN-LAST:event_libeleeMouseClicked

    private void benificiaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_benificiaireMouseClicked
        // TODO add your handling code here:
        benificiaire.setText("");
    }//GEN-LAST:event_benificiaireMouseClicked

    private void datepaieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datepaieMouseClicked

        datepaie.setDate(null);
    }//GEN-LAST:event_datepaieMouseClicked

    private void montantdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_montantdMouseClicked
        // TODO add your handling code here:
        montantd.setText("");
    }//GEN-LAST:event_montantdMouseClicked

    private void tdepenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdepenseMouseClicked
        // TODO add your handling code here:
        try{

           int row=tdepense.getSelectedRow();
           String ID=(tdepense.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from depenses where id_depense= '"+id+"' ");

          rs = pstmt1.executeQuery();

if (rs.next())
{
   String lib=rs.getString("libele");
  libelee.setText(lib);
  int montan=rs.getInt("montant");
 montantd.setText(Integer.toString(montan));
Date dp=rs.getDate("date");
datepaie.setDate(dp);
String benif=rs.getString("benificiaire");
benificiaire.setText(benif);

}

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}


    }//GEN-LAST:event_tdepenseMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
         Font Header3 =FontFactory.getFont("Arial",BaseFont.IDENTITY_H,9,Font.NORMAL);
     Document document = new Document();
     String NomFichierPDF = "depense.pdf";

            try
      {
      PdfWriter.getInstance(document,new FileOutputStream(NomFichierPDF)).setInitialLeading(13f);
      document.open();
      Calendar cal=new GregorianCalendar() ;
      int Y=cal.get(Calendar.YEAR);
  int M=cal.get(Calendar.MONTH);
  int d=cal.get(Calendar.DAY_OF_MONTH);
  String datecurrent=Y+"-"+(M+1)+"-"+d ;
Image image=Image.getInstance("log.jpg");
      document.add(image);
      document.add(new Paragraph("                                                                                                    "));
      document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                         Fiche de paie dépense"));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                     "+datecurrent+"                "));
document.add(new Paragraph("                                                                        "));

      PdfPTable Table = new PdfPTable(2);

      Table.setWidthPercentage(70f);

      Table.setWidths(new int []{50,50});
       int row=tdepense.getSelectedRow();
           String ID=(tdepense.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from depenses where id_depense= '"+id+"' ");

          rs = pstmt1.executeQuery();
String libele="";
String montant="";
String benifi="";
String date="";
if (rs.next())
{
   String lib=rs.getString("libele");
  int montan=rs.getInt("montant");
Date dp=rs.getDate("date");
date=dp.toString();
montant=Integer.toString(montan);
libele=lib;
String benif=rs.getString("benificiaire");
benifi=benif;
}

      
     Table.addCell("Id dépense");
      Table.addCell(ID);
      Table.addCell("libelé");
      Table.addCell(libele);
      Table.addCell("Montant payé");
      Table.addCell(montant);
      Table.addCell("Benificiaire");
      Table.addCell(benifi);
      Table.addCell("Date de paie");
      Table.addCell(date);

     

      document.add(Table);
      
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("Centre de la formation professionnel                                           Signature Directrice "));
document.add(new Paragraph("Avenue 14 Janvier Rue Ahmed Aloulou                                                                 "));
document.add(new Paragraph("Imm. Ragheb étage. 2 App. 4 -Sfax                                                                                                   "));

document.close();

imprime();
      }catch(Exception e)
      {
      System.out.println(e.getMessage());
      }

    }//GEN-LAST:event_jButton6MouseClicked

    private void libeleeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_libeleeKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_SPACE  || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_libeleeKeyTyped

    private void montantdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montantdKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }

    }//GEN-LAST:event_montantdKeyTyped

    private void benificiaireKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_benificiaireKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_SPACE  || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_benificiaireKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new depense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField benificiaire;
    private com.toedter.calendar.JDateChooser datepaie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libelee;
    private javax.swing.JTextField montantd;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JTable tdepense;
    // End of variables declaration//GEN-END:variables

}
