/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AjoutF.java
 *
 * Created on 29 avr. 2014, 13:58:34
 */

package graphique;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils ;

/**
 *
 * @author zied_2
 */
public class Fco extends javax.swing.JFrame {
Connection conn =connexion_bd.connexion();
ResultSet rs;
    /** Creates new form AjoutF */
    public Fco() {
        initComponents();
 conn =connexion_bd.connexion();
 
 
 modif_fco();
 update_fco();
 list_matier_fco();
 this.setTitle("formation continue");
 
 annule_f();
 
 
 

    }
  //////*************gestion formation continue************************

 
  private void modif_fco()
  {

  }
  private void update_fco()
  {
try{

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from formation_co ");

          rs = pstmt1.executeQuery();

fco.setModel(DbUtils.resultSetToTableModel(rs));

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
  }
 
  private void list_matier_fco()
  {

  }
  ///////************gestion formation Court Terme*********************
 
 
 
 
 
  /////*********vider les champs de tous les formulaire***************
  private void annule_f()
  {
  
  nf.setText("");
  pm.setText("");
 
  jDateChooser2.setDate(null);
  jDateChooser1.setDate(null);
  jTextField1.setText("Nom formation");
  
  }




    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        fco = new javax.swing.JTable();
        pm = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        panel2 = new java.awt.Panel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        ajout = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        nf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1070, 650));
        getContentPane().setLayout(null);

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(840, 340, 170, 40);

        fco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        fco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fcoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(fco);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 700, 450);

        pm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmMouseClicked(evt);
            }
        });
        pm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pmKeyTyped(evt);
            }
        });
        getContentPane().add(pm);
        pm.setBounds(840, 220, 170, 40);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "     ", "niveau 1", "niveau 2", "niveau 3", "niveau 4", "professionel" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(840, 100, 170, 40);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(840, 280, 170, 40);

        panel2.setBackground(new java.awt.Color(51, 255, 255));
        panel2.setLayout(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-4878-32.png"))); // NOI18N
        jButton3.setText("Supprimer");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        panel2.add(jButton3);
        jButton3.setBounds(180, 20, 140, 50);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/kedit-icone-8843-32.png"))); // NOI18N
        jButton4.setText("Modifier ");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        panel2.add(jButton4);
        jButton4.setBounds(330, 20, 140, 50);

        ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ajouter-crayon-icone-4828-32.png"))); // NOI18N
        ajout.setText("Ajouter formation");
        ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutMouseClicked(evt);
            }
        });
        panel2.add(ajout);
        ajout.setBounds(10, 20, 153, 50);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-7248-32.png"))); // NOI18N
        jButton6.setText("Annuler");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        panel2.add(jButton6);
        jButton6.setBounds(480, 20, 150, 50);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/recherche-icone-4239-32.png"))); // NOI18N
        jButton7.setText("Chercher");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        panel2.add(jButton7);
        jButton7.setBounds(330, 80, 140, 40);

        jTextField1.setText("Nom formation");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        panel2.add(jTextField1);
        jTextField1.setBounds(10, 80, 150, 40);

        jButton1.setText("Gérer matières");
        jButton1.setActionCommand("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        panel2.add(jButton1);
        jButton1.setBounds(480, 80, 150, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "niveau 1", "niveau 2", "niveau 3", "niveau 4", "professionel" }));
        panel2.add(jComboBox1);
        jComboBox1.setBounds(180, 80, 140, 40);

        getContentPane().add(panel2);
        panel2.setBounds(10, 480, 1010, 130);

        nf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nfMouseClicked(evt);
            }
        });
        nf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nfKeyTyped(evt);
            }
        });
        getContentPane().add(nf);
        nf.setBounds(840, 160, 170, 40);

        jLabel2.setText("Formation:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(750, 164, 90, 30);

        jLabel3.setText("Niveau:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 104, 80, 30);

        jLabel4.setText("Prix_mois:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(750, 220, 80, 40);

        jLabel5.setText("Date debut:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(750, 280, 80, 30);

        jLabel6.setText("Date fin:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(750, 340, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/a_p.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-310, -60, 1370, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents
///***************Action sur bouttons et apel du fonctions***********************

    private void nfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nfMouseClicked
        // TODO add your handling code here:
        nf.setText("");
    }//GEN-LAST:event_nfMouseClicked

    private void pmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmMouseClicked
        // TODO add your handling code here:
        pm.setText("");
    }//GEN-LAST:event_pmMouseClicked

    private void ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMouseClicked
        // TODO add your handling code here:
           
       
         try
     {
             String niv=jComboBox2.getSelectedItem().toString();
             String form=nf.getText();
              PreparedStatement pstmt2 = conn.prepareStatement("select * from formation_co where nom_formation= '"+form+"' and niveau='"+niv+"' ");
     rs=pstmt2.executeQuery();
     if (rs.next())
     {
          JOptionPane.showMessageDialog(null,"formation existe déja");
     }
     else
     {
         PreparedStatement pstmt1=conn.prepareStatement("insert into formation_co (niveau,nom_formation,prix_par_mois,date_debut,date_fin) values (?,?,?,?,?)");

pstmt1.setString(1,niv);
pstmt1.setString(2,nf.getText());
pstmt1.setInt(3,Integer.parseInt(pm.getText()));
pstmt1.setString(4,((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
pstmt1.setString(5,((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText());
                java.util.Date dd=jDateChooser1.getDate();
                java.util.Date df=jDateChooser2.getDate();
                if (dd.after(df))
                {
               JOptionPane.showMessageDialog(null,"date de fin doit ètre après la date de debut");
                }
                else{
      int resultat = pstmt1.executeUpdate();
       JOptionPane.showMessageDialog(null,"formation enregistrer");
                }
     }
     }
     catch(Exception e)
     {
    System.out.println(e.getMessage());

	    	}
         update_fco();
         annule_f();
         
    }//GEN-LAST:event_ajoutMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        

  try{
              int row=fco.getSelectedRow();
 String ID=(fco.getModel().getValueAt(row, 0).toString());
           int idf ;
           idf=Integer.parseInt(ID);

 String nive=(fco.getModel().getValueAt(row, 1).toString());
           String form=(fco.getModel().getValueAt(row, 2).toString());
           String tp="FCO";

PreparedStatement pstmt2 = conn.prepareStatement("select * from  inscription   where formation= '"+form+"' and niveau='"+nive+"' and type_formation='"+tp+"' ");
rs=pstmt2.executeQuery();
if(rs.next())
{
 JOptionPane.showMessageDialog(null,"Erreur de modification, il'y a des étudiants qui ont inscrivé");
}
else {
String niv=jComboBox2.getSelectedItem().toString();
String nomf=nf.getText();
int prixheure=Integer.parseInt(pm.getText());
String dated=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
String datef=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();



        PreparedStatement pstmt1 = conn.prepareStatement("update  formation_co set niveau='"+niv+"',nom_formation='"+nomf+"' , prix_par_mois='"+prixheure+"' ,date_debut='"+dated+"',date_fin='"+datef+"'  where id_form= '"+idf+"' ");

java.util.Date dd=jDateChooser1.getDate();
                java.util.Date df=jDateChooser2.getDate();
                if (dd.after(df))
                {
               JOptionPane.showMessageDialog(null,"date de fin doit ètre après la date de debut");
                }
                else{


         int resultat = pstmt1.executeUpdate();


	    		 JOptionPane.showMessageDialog(null,"mise à jour effectuer");

                }

}
	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
         update_fco ();


        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
annule_f();

    }//GEN-LAST:event_jButton6MouseClicked

    private void fcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fcoMouseClicked
        // TODO add your handling code here:
try{

           int row=fco.getSelectedRow();
           String ID=(fco.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from formation_co where id_form= '"+id+"' ");

          rs = pstmt1.executeQuery();


while (rs.next())
{


Date d1=rs.getDate("date_debut");
Date d2=rs.getDate("date_fin");
jDateChooser1.setDate(d1);
jDateChooser2.setDate(d2);
String niv=rs.getString("niveau");
String nomf=rs.getString("nom_formation");
nf.setText(nomf);


int phr=rs.getInt("prix_par_mois");

pm.setText(Integer.toString(phr));




}


	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
    }//GEN-LAST:event_fcoMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        int c=JOptionPane.showConfirmDialog(null,"tu veux supprimer"," supprime",JOptionPane.YES_NO_OPTION);
        if(c==0){
         try{
              int row=fco.getSelectedRow();
 String ID=(fco.getModel().getValueAt(row, 0).toString());
           int idf ;
           idf=Integer.parseInt(ID);
           String niv=(fco.getModel().getValueAt(row, 1).toString());
           String form=(fco.getModel().getValueAt(row, 2).toString());
           String tp="FCO";

PreparedStatement pstmt2 = conn.prepareStatement("select * from  inscription   where formation= '"+form+"' and niveau='"+niv+"' and type_formation='"+tp+"' ");
rs=pstmt2.executeQuery();
if(rs.next())
{
 JOptionPane.showMessageDialog(null,"Erreur suppression, il'y a des étudiants qui ont inscrivé");
}
else {
        PreparedStatement pstmt1 = conn.prepareStatement("delete from  formation_co   where id_form= '"+idf+"' ");




         int resultat = pstmt1.executeUpdate();


	    		 JOptionPane.showMessageDialog(null,"suppression effectuer");


}

	    }
	    	catch(Exception e){
	    		System.out.println(e.getMessage());

	    	}}
         update_fco ();


    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         heures_enseigner  appelfenetre=new   heures_enseigner();
         appelfenetre.setLocationRelativeTo(null);
        appelfenetre.setVisible(true) ;
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        String nomf=jTextField1.getText();
        String niv=jComboBox1.getSelectedItem().toString();
        try
        {
         PreparedStatement pstmt1 = conn.prepareStatement("select * from formation_co where nom_formation='"+nomf+"' and niveau='"+niv+"'");
          rs = pstmt1.executeQuery();
         if (rs.next())
         {
          Date d1=rs.getDate("date_debut");
Date d2=rs.getDate("date_fin");
jDateChooser1.setDate(d1);
jDateChooser2.setDate(d2);
String nivea=rs.getString("niveau");
String nomfor=rs.getString("nom_formation");
nf.setText(nomfor);


int phr=rs.getInt("prix_par_mois");

pm.setText(Integer.toString(phr));
         }
          else
{
 JOptionPane.showMessageDialog(null,"Formation n'existe pas");
}
        }
        catch(Exception e)
        {
System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void nfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nfKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_SPACE  || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }

    }//GEN-LAST:event_nfKeyTyped

    private void pmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pmKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }

    }//GEN-LAST:event_pmKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajout;
    private javax.swing.JTable fco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nf;
    private java.awt.Panel panel2;
    private javax.swing.JTextField pm;
    // End of variables declaration//GEN-END:variables

}
