package graphique;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formateur.java
 *
 * Created on 17 avr. 2014, 13:00:33
 */

import java.sql.*;

import net.proteanit.sql.DbUtils ;
import javax.swing.* ;
import java.awt.* ;
import java.awt.event.KeyEvent;



public class formateur extends javax.swing.JFrame {
ResultSet rs =null ;
Connection conn=connexion_bd.connexion();
    /** Creates new form formateur */
    public formateur() {
        initComponents();
        ajout_formateur();
        chercher_formateur();
        modifier_formateur();
        update_formateur();
        annule();
        conn=connexion_bd.connexion();
        this.setTitle("Formateur");
    }
    private void annule()
            //code pour vider les champ
    {
 cin.setText("");
        nom.setText("");
        prenom.setText("");
        num_tel.setText("");
        adresse.setText("");
        mail.setText("");
        jTextField1.setText("recherche par cin");
    }
    private void ajout_formateur()
            // code ajout formateur
    {
      
      try{
          int cinf=Integer.parseInt(cin.getText());
      PreparedStatement pstmt2 = conn.prepareStatement("select * from formateur where cin_formateur= '"+cinf+"' ");

          rs = pstmt2.executeQuery();

if (rs.next())
{
 JOptionPane.showMessageDialog(null,"formateur existe déja");
}
else   {
 

	    		PreparedStatement pstmt1 = conn.prepareStatement("insert into formateur (cin_formateur,nom,prenom,num_tel,adresse,mail) values (?,?,?,?,?,?)");


        pstmt1.setInt(1,Integer.parseInt(cin.getText()));
 pstmt1.setString(2,nom.getText());
  pstmt1.setString(3,prenom.getText());
   pstmt1.setInt(4,Integer.parseInt(num_tel.getText()));
    pstmt1.setString(5,adresse.getText());
     pstmt1.setString(6,mail.getText());

         int resultat = pstmt1.executeUpdate();



	    		 JOptionPane.showMessageDialog(null,"formateur enregistrer");
	    }}
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
         update_formateur ();
    }
     private void chercher_formateur()
             //code pour supprimer un formateur
     {
 try{


           int cinf ;
           cinf=Integer.parseInt(jTextField1.getText());

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from formateur where cin_formateur= '"+cinf+"' ");

          rs = pstmt1.executeQuery();

if (rs.next())
{
   int cinfor=rs.getInt("cin_formateur");
  cin.setText(Integer.toString(cinfor));
  int num_telf=rs.getInt("num_tel");
 num_tel.setText(Integer.toString(num_telf));


String nomf=rs.getString("nom");
nom.setText(nomf);
String prenf=rs.getString("prenom");
prenom.setText(prenf);
String adrf=rs.getString("adresse");
adresse.setText(adrf);
String mailf=rs.getString("mail");
mail.setText(mailf);

}
else
{
 JOptionPane.showMessageDialog(null,"formateur n'existe pas");
}
	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
     }
     private void modifier_formateur()
             //code pour modifier un formateur
     {
try{
              int row=formateur_table.getSelectedRow();
 String ID=(formateur_table.getModel().getValueAt(row, 0).toString());
           int cinformateur ;
           cinformateur=Integer.parseInt(ID);


String tel=num_tel.getText();
int num_telf=Integer.parseInt(tel);
String nomf=nom.getText();
String pren=prenom.getText();
String adressef=adresse.getText();
String mailfor=mail.getText();

	     


        PreparedStatement pstmt1 = conn.prepareStatement("update  formateur set nom='"+nomf+"',prenom='"+pren+"',num_tel='"+num_telf+"',adresse='"+adressef+"', mail='"+mailfor+"'  where cin_formateur= '"+cinformateur+"' ");




         int resultat = pstmt1.executeUpdate();


	    		 JOptionPane.showMessageDialog(null,"mise à jour effectuer");




	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
         update_formateur ();



     }
     private void update_formateur()
             //mise à jour de jtable contenu
     {
     try{
	      
	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from formateur  ");

          rs = pstmt1.executeQuery();

formateur_table.setModel(DbUtils.resultSetToTableModel(rs));

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
     }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        formateur_table = new javax.swing.JTable();
        nom = new javax.swing.JTextField();
        num_tel = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        adresse = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        panel1 = new java.awt.Panel();
        annuler = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ajout = new javax.swing.JButton();
        supprime = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        formateur_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        formateur_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formateur_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(formateur_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 690, 300);

        nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomMouseClicked(evt);
            }
        });
        nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomKeyTyped(evt);
            }
        });
        getContentPane().add(nom);
        nom.setBounds(850, 210, 160, 40);

        num_tel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                num_telMouseClicked(evt);
            }
        });
        num_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_telActionPerformed(evt);
            }
        });
        num_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                num_telKeyTyped(evt);
            }
        });
        getContentPane().add(num_tel);
        num_tel.setBounds(850, 330, 160, 40);

        prenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prenomMouseClicked(evt);
            }
        });
        prenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prenomKeyTyped(evt);
            }
        });
        getContentPane().add(prenom);
        prenom.setBounds(850, 270, 160, 40);

        mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mailMouseClicked(evt);
            }
        });
        getContentPane().add(mail);
        mail.setBounds(850, 450, 160, 40);

        adresse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adresseMouseClicked(evt);
            }
        });
        adresse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                adresseKeyTyped(evt);
            }
        });
        getContentPane().add(adresse);
        adresse.setBounds(850, 390, 160, 40);

        cin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cinMouseClicked(evt);
            }
        });
        cin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cinKeyTyped(evt);
            }
        });
        getContentPane().add(cin);
        cin.setBounds(850, 150, 160, 40);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(null);

        annuler.setBackground(new java.awt.Color(204, 204, 255));
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-7248-32.png"))); // NOI18N
        annuler.setText("annuler");
        annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annulerMouseClicked(evt);
            }
        });
        panel1.add(annuler);
        annuler.setBounds(430, 10, 200, 50);

        edit.setBackground(new java.awt.Color(204, 204, 255));
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/kedit-icone-8843-32.png"))); // NOI18N
        edit.setText("modifier");
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        panel1.add(edit);
        edit.setBounds(240, 10, 180, 50);

        jTextField1.setText("recherche par cin");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        panel1.add(jTextField1);
        jTextField1.setBounds(40, 10, 180, 50);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/recherche-icone-4239-32.png"))); // NOI18N
        jButton1.setText("recherche");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        panel1.add(jButton1);
        jButton1.setBounds(40, 70, 180, 50);

        ajout.setBackground(new java.awt.Color(204, 204, 255));
        ajout.setForeground(new java.awt.Color(255, 255, 255));
        ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ajouter-crayon-icone-4828-32.png"))); // NOI18N
        ajout.setText("ajouter");
        ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutMouseClicked(evt);
            }
        });
        panel1.add(ajout);
        ajout.setBounds(240, 70, 180, 50);

        supprime.setBackground(new java.awt.Color(204, 204, 255));
        supprime.setForeground(new java.awt.Color(255, 255, 255));
        supprime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-4878-32.png"))); // NOI18N
        supprime.setText("supprimer");
        supprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimeMouseClicked(evt);
            }
        });
        panel1.add(supprime);
        supprime.setBounds(430, 70, 200, 50);

        getContentPane().add(panel1);
        panel1.setBounds(40, 410, 690, 130);

        jLabel2.setText("Cin formateur");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(750, 154, 80, 30);

        jLabel3.setText("Nom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(750, 220, 80, 30);

        jLabel4.setText("Prénom");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(750, 280, 70, 30);

        jLabel5.setText("Num téléphone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(750, 340, 100, 20);

        jLabel6.setText("Adresse");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(750, 400, 90, 20);

        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(750, 460, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/a_p.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-310, 0, 1410, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMouseClicked
        // operation insertion formateur:
        ajout_formateur();
          annule();
    }//GEN-LAST:event_ajoutMouseClicked

    private void supprimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimeMouseClicked
        // TODO add your handling code here:
         int c=JOptionPane.showConfirmDialog(null,"Voulez vous vraiment supprimer?"," supprime",JOptionPane.YES_NO_OPTION);
        if(c==0){
        try{

           int row=formateur_table.getSelectedRow();
           String CINF=(formateur_table.getModel().getValueAt(row, 0).toString());
           int cinf ;
           cinf=Integer.parseInt(CINF);

	    		PreparedStatement pstmt1 = conn.prepareStatement("delete  from formateur where cin_formateur= '"+cinf+"' ");

         int resultat= pstmt1.executeUpdate();

JOptionPane.showMessageDialog(null,"suppression éffectuer avec succes");

}


	    	catch(Exception E){
	    		System.out.println(E.getMessage());

	    	}}
         update_formateur ();

         annule();
    }//GEN-LAST:event_supprimeMouseClicked

    private void formateur_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formateur_tableMouseClicked
        // TODO add your handling code here:
         try{

           int row=formateur_table.getSelectedRow();
           String ID=(formateur_table.getModel().getValueAt(row, 0).toString());
           int cinf ;
           cinf=Integer.parseInt(ID);
	     
	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from formateur where cin_formateur= '"+cinf+"' ");

          rs = pstmt1.executeQuery();

if (rs.next())
{
   int cinfor=rs.getInt("cin_formateur");
  cin.setText(Integer.toString(cinfor));
  int num_telf=rs.getInt("num_tel");
 num_tel.setText(Integer.toString(num_telf));


String nomf=rs.getString("nom");
nom.setText(nomf);
String prenf=rs.getString("prenom");
prenom.setText(prenf);
String adrf=rs.getString("adresse");
adresse.setText(adrf);
String mailf=rs.getString("mail");
mail.setText(mailf);

}

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}

    }//GEN-LAST:event_formateur_tableMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
        // TODO add your handling code here:
        modifier_formateur();
         annule();
    }//GEN-LAST:event_editMouseClicked

    private void num_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_telActionPerformed

    private void nomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMouseClicked
        // TODO add your handling code here:
        nom.setText("");
    }//GEN-LAST:event_nomMouseClicked

    private void prenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseClicked
        // TODO add your handling code here:
        prenom.setText("");
    }//GEN-LAST:event_prenomMouseClicked

    private void num_telMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_num_telMouseClicked
        // TODO add your handling code here:
        num_tel.setText("");
    }//GEN-LAST:event_num_telMouseClicked

    private void adresseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adresseMouseClicked
        // TODO add your handling code here:
        adresse.setText("");
    }//GEN-LAST:event_adresseMouseClicked

    private void mailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailMouseClicked
        // TODO add your handling code here:
        mail.setText("");
    }//GEN-LAST:event_mailMouseClicked

    private void annulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annulerMouseClicked
        // TODO add your handling code here:
         annule();
    }//GEN-LAST:event_annulerMouseClicked

    private void cinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cinMouseClicked
        // TODO add your handling code here:
        cin.setText("");
    }//GEN-LAST:event_cinMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        chercher_formateur();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void cinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cinKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_cinKeyTyped

    private void num_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_num_telKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_num_telKeyTyped

    private void nomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_SPACE  || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_nomKeyTyped

    private void prenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prenomKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_SPACE  || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_prenomKeyTyped

    private void adresseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adresseKeyTyped
        // TODO add your handling code here:
          char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_MINUS || c==KeyEvent.VK_DECIMAL|| c==KeyEvent.VK_SPACE  || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_adresseKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse;
    private javax.swing.JButton ajout;
    private javax.swing.JButton annuler;
    private javax.swing.JTextField cin;
    private javax.swing.JButton edit;
    private javax.swing.JTable formateur_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField num_tel;
    private java.awt.Panel panel1;
    private javax.swing.JTextField prenom;
    private javax.swing.JButton supprime;
    // End of variables declaration//GEN-END:variables

}
