/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * matiere.java
 *
 * Created on 6 mars 2014, 10:37:51
 */

package graphique;

/**
 *
 * @author zied
 */


import java.awt.event.KeyEvent;
import java.sql.*;

import net.proteanit.sql.DbUtils ;
import javax.swing.* ;

public class matiere extends javax.swing.JFrame {
ResultSet rs =null ;
Connection conn=connexion_bd.connexion();

    /** Creates new form matiere */
    public matiere() {
        initComponents();
         update_matiere ();
         conn=connexion_bd.connexion();
        this.setTitle("Gestionnaire de matières");
    }
private void update_matiere ()
{

 try{
	      
	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from matiere ORDER BY  `id_matiere` ASC ");

          rs = pstmt1.executeQuery();

table_matier.setModel(DbUtils.resultSetToTableModel(rs));
	    		
	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}

}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_matier = new javax.swing.JTable();
        supprime = new javax.swing.JButton();
        edite = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nom_matiere = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(1070, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(null);

        table_matier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_matier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_matierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_matier);

        panel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 60, 452, 310);

        supprime.setBackground(new java.awt.Color(0, 204, 204));
        supprime.setForeground(new java.awt.Color(255, 255, 255));
        supprime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-4878-32.png"))); // NOI18N
        supprime.setText("supprimer");
        supprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimeMouseClicked(evt);
            }
        });
        panel1.add(supprime);
        supprime.setBounds(520, 390, 130, 50);

        edite.setBackground(new java.awt.Color(0, 204, 204));
        edite.setForeground(new java.awt.Color(255, 255, 255));
        edite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/kedit-icone-8843-32.png"))); // NOI18N
        edite.setText("modifier");
        edite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editeMouseClicked(evt);
            }
        });
        panel1.add(edite);
        edite.setBounds(370, 390, 140, 50);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ajouter-crayon-icone-4828-32.png"))); // NOI18N
        jButton1.setText("ajouter matière");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1);
        jButton1.setBounds(200, 390, 150, 50);

        nom_matiere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nom_matiereMouseClicked(evt);
            }
        });
        nom_matiere.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nom_matiereKeyTyped(evt);
            }
        });
        panel1.add(nom_matiere);
        nom_matiere.setBounds(30, 390, 150, 50);

        jLabel2.setText("Matière:");
        panel1.add(jLabel2);
        jLabel2.setBounds(30, 364, 100, 20);

        getContentPane().add(panel1);
        panel1.setBounds(100, 50, 800, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logooo copie.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-40, -110, 1450, 910);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String mat=nom_matiere.getText();
            PreparedStatement pstmt2 = conn.prepareStatement("select * from matiere where nom_matiere= '"+mat+"' ");

          rs = pstmt2.executeQuery();

if (rs.next())
{
    JOptionPane.showMessageDialog(null,"matiere déja existe");
}
else{
	    		PreparedStatement pstmt1 = conn.prepareStatement("insert into matiere (nom_matiere) values (?)");

       
         pstmt1.setString(1,nom_matiere.getText());


         int resultat = pstmt1.executeUpdate();



	    		 JOptionPane.showMessageDialog(null,"matiere ajouter");
	    }}
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
         update_matiere ();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_matierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_matierMouseClicked
        // TODO add your handling code here:
        try{

           int row=table_matier.getSelectedRow();
           String ID=(table_matier.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);
	     
	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from matiere where id_matiere= '"+id+"' ");

          rs = pstmt1.executeQuery();

if (rs.next())
{
  


String matiere=rs.getString("nom_matiere");
nom_matiere.setText(matiere);


}

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}

    }//GEN-LAST:event_table_matierMouseClicked

    private void supprimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimeMouseClicked
        // TODO add your handling code here:
        int c=JOptionPane.showConfirmDialog(null,"tu veux supprimer"," supprime",JOptionPane.YES_NO_OPTION);
        if(c==0){
        try{

           int row=table_matier.getSelectedRow();
           String ID=(table_matier.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);
	     
	    		PreparedStatement pstmt1 = conn.prepareStatement("delete  from matiere where id_matiere= '"+id+"' ");

         int resultat= pstmt1.executeUpdate();

JOptionPane.showMessageDialog(null,"matière supprimer avec succes");

}


	    	catch(Exception e){
	    		System.out.println(e.getMessage());

	    	}}
         update_matiere ();

    }//GEN-LAST:event_supprimeMouseClicked

    private void editeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editeMouseClicked
        // TODO add your handling code here:
        try{
              int row=table_matier.getSelectedRow();
 String ID=(table_matier.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);

String matiere=nom_matiere.getText();

	      


        PreparedStatement pstmt1 = conn.prepareStatement("update  matiere set nom_matiere='"+matiere+"' where id_matiere= '"+id+"' ");




         int resultat = pstmt1.executeUpdate();


	    		 JOptionPane.showMessageDialog(null,"mise à jour effectuer");
          nom_matiere.setText("");



	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
         update_matiere ();



    }//GEN-LAST:event_editeMouseClicked

    private void nom_matiereKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_matiereKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_PERIOD || c==KeyEvent.VK_SPACE  || c==KeyEvent.VK_BACK_SPACE ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_nom_matiereKeyTyped

    private void nom_matiereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom_matiereMouseClicked
        // TODO add your handling code here:
        nom_matiere.setText("");
    }//GEN-LAST:event_nom_matiereMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matiere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edite;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nom_matiere;
    private java.awt.Panel panel1;
    private javax.swing.JButton supprime;
    private javax.swing.JTable table_matier;
    // End of variables declaration//GEN-END:variables

}
