/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * parametre.java
 *
 * Created on 20 mars 2014, 22:28:08
 */

package graphique;

import java.sql.*;
import javax.swing.*;
import java.awt.* ;
import java.awt.event.KeyEvent;
/**
 *
 * @author zied_2
 */
public class parametre extends javax.swing.JFrame {
 ResultSet rs=null ;
 Connection conn=connexion_bd.connexion();
    /** Creates new form parametre */
    public parametre() {
        initComponents();
        modifier_parametre();
        conn=connexion_bd.connexion();
        this.setTitle("Paramètres");
    }
    private void modifier_parametre()
    {
        String loginn=log1.getText();
         String login2=log2.getText();
        String pswd11=pswd1.getText();
        String pswd22=pswd2.getText();
        String pswd33=pswd3.getText();
        try{
	      
	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from admin");

          rs = pstmt1.executeQuery();
          while(rs.next())
      {
          String login=rs.getString("login");
          String psword=rs.getString("pswd");

          if(( pswd11.length()>0 &&loginn.length()>0)&&( !psword.equals(pswd11) || !login.equals(loginn)))
          {

           JOptionPane.showMessageDialog(null,"verifier vos paramètres ");
          }
          else if(( pswd22.length()>0 &&pswd33.length()>0 &&login2.length()>0)&&( pswd22.equals(pswd33) && login.equals(loginn)))
            {

              PreparedStatement pstmt2 = conn.prepareStatement("update admin set login='"+login2+"',pswd='"+pswd22+"'");

          int resultat = pstmt2.executeUpdate();
JOptionPane.showMessageDialog(null,"parametres effectuer");
            }
          }





	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}




    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        log1 = new javax.swing.JTextField();
        log2 = new javax.swing.JTextField();
        pswd1 = new javax.swing.JPasswordField();
        pswd2 = new javax.swing.JPasswordField();
        pswd3 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(-13108,true));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/correct.png"))); // NOI18N
        jButton1.setText("enregistrer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 420, 180, 40);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-7248-32.png"))); // NOI18N
        jButton2.setText("annuler");
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 420, 200, 40);

        panel1.setBackground(new java.awt.Color(255, 204, 204));
        panel1.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(-1,true));
        jLabel4.setText("Nouveau mot de passe:");
        panel1.add(jLabel4);
        jLabel4.setBounds(130, 260, 160, 30);

        jLabel5.setForeground(new java.awt.Color(-1,true));
        jLabel5.setText("Confirmer mot de passe:");
        panel1.add(jLabel5);
        jLabel5.setBounds(130, 330, 180, 30);

        jLabel3.setForeground(new java.awt.Color(-1,true));
        jLabel3.setText("Mot de passe actuel:");
        panel1.add(jLabel3);
        jLabel3.setBounds(130, 190, 160, 30);

        jLabel2.setForeground(new java.awt.Color(-1,true));
        jLabel2.setText("Nouvel login:");
        panel1.add(jLabel2);
        jLabel2.setBounds(130, 110, 150, 40);

        jLabel1.setForeground(new java.awt.Color(-1,true));
        jLabel1.setText("Login actuel:");
        panel1.add(jLabel1);
        jLabel1.setBounds(130, 50, 150, 39);

        log1.setFont(new java.awt.Font("Tahoma", 1, 14));
        log1.setForeground(new java.awt.Color(255, 153, 153));
        panel1.add(log1);
        log1.setBounds(340, 40, 204, 39);

        log2.setFont(new java.awt.Font("Tahoma", 1, 14));
        log2.setForeground(new java.awt.Color(255, 153, 153));
        panel1.add(log2);
        log2.setBounds(340, 110, 204, 41);
        panel1.add(pswd1);
        pswd1.setBounds(340, 180, 204, 40);
        panel1.add(pswd2);
        pswd2.setBounds(340, 250, 204, 40);

        pswd3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswd3KeyPressed(evt);
            }
        });
        panel1.add(pswd3);
        pswd3.setBounds(340, 320, 200, 40);

        getContentPane().add(panel1);
        panel1.setBounds(210, 40, 610, 530);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logooo copie.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-20, -80, 1440, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        modifier_parametre();
    }//GEN-LAST:event_jButton1MouseClicked

    private void pswd3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswd3KeyPressed
        // TODO add your handling code here:
          if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
           modifier_parametre();

          }
    }//GEN-LAST:event_pswd3KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new parametre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField log1;
    private javax.swing.JTextField log2;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField pswd1;
    private javax.swing.JPasswordField pswd2;
    private javax.swing.JPasswordField pswd3;
    // End of variables declaration//GEN-END:variables

}
