/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * recape.java
 *
 * Created on 31 mai 2014, 13:33:23
 */

package graphique;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPTable;

import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;

import java.io.FileOutputStream;

import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;



/**
 *
 * @author zied_2
 */
public class recape extends javax.swing.JFrame {
Connection conn=connexion_bd.connexion();
ResultSet rs,rs2,rs3,rs4;
    /** Creates new form recape */
    public recape() {
        initComponents();
        conn=connexion_bd.connexion();
        this.setTitle("Récape générale");
    }
    private void imprime()
    {
          try
        {
    Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\zied_2\\Documents\\NetBeansProjects\\Gesfor\\dist\\rc.pdf");
        }
    catch(Exception e)
    {
      System.out.println(e.getMessage());
    }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(60, 140, 160, 28);

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(290, 140, 152, 28);

        jLabel1.setText("Récape générale de opération financière efféctue entre");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 60, 330, 30);

        jLabel2.setText("et");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 140, 34, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/print.jpg"))); // NOI18N
        jButton1.setText("imprimer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 210, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        java.util.Date dd=jDateChooser1.getDate();
                java.util.Date df=jDateChooser2.getDate();
                if (dd.after(df))
                {
               JOptionPane.showMessageDialog(null,"date de fin doit ètre après la date de debut");
                }
                else{
        Font Header3 =FontFactory.getFont("Arial",BaseFont.IDENTITY_H,14,Font.NORMAL,Color.LIGHT_GRAY);
     Document document = new Document(PageSize.A4);
     String NomFichierPDF = "rc.pdf";


            try
      {
      PdfWriter.getInstance(document,new FileOutputStream(NomFichierPDF)).setInitialLeading(13f);
      document.open();
      Calendar cal=new GregorianCalendar() ;
      int Y=cal.get(Calendar.YEAR);
  int M=cal.get(Calendar.MONTH);
  int d=cal.get(Calendar.DAY_OF_MONTH);

  String mm="";
  if (M==1)
  {
   mm="Février";
  }
  else if (M==2)
  {
   mm="Mars" ;
  }
  else if (M==3)
  {
  mm="Avril";
  }
  else if (M==4)
  {
    mm="Mai" ;
  }
  else if (M==5)
  {
     mm="Juin";
  }
  else if (M==6)
  {
     mm="Juillet" ;
  }
   else if (M==7)
  {
     mm= "Aout";
  }
   else if (M==8)
  {
     mm="Séptembre";
  }
   else if (M==9)
  {
     mm= "Octobre";
  }
   else if (M==10)
  {
     mm= "Novembre";
  }
   else if (M==11)
  {
     mm="Décembre" ;
  }
   else if (M==12)
  {
     mm="Janvier";
  }

            String d1=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
            String d2=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
           
Image image=Image.getInstance("log.jpg");

      document.add(image);
      document.add(new Paragraph("                                                             Recape Générale                                                             "));
      document.add(new Paragraph("                                                                 "+d+" "+mm+" "+Y+"                                                           "));
      document.add(new Paragraph("                                                                                                    "));
      document.add(new Paragraph("                                                                                                    "));




document.add(new Paragraph("Liste de dépense :",Header3));
 document.add(new Paragraph("                                                                                                    "));
/////////////liste de dépenses////////////////////
 PdfPTable Table = new PdfPTable(3);

      Table.setWidthPercentage(70f);

      Table.setWidths(new int []{35,30,35});
 Table.addCell("Bénificiaire: ");
 Table.addCell("Montant:");
    Table.addCell("effectue le:");
PreparedStatement pstmt1 = conn.prepareStatement("select * from depenses where date <'"+d2+"' and date >'"+d1+"' ");

          rs = pstmt1.executeQuery();
int tot=0;
          while(rs.next())
          {

int mont=rs.getInt("montant");
String benif=rs.getString("benificiaire");
Date D=rs.getDate("date");
tot=tot+mont;
Table.addCell(benif);
 Table.addCell(Integer.toString(mont)) ;
 Table.addCell(D.toString());
          }
Table.addCell("");
Table.addCell("");
Table.addCell("");
Table.addCell("");
Table.addCell("total:");
 Table.addCell(Integer.toString(tot)) ;

          document.add(Table);

document.add(new Paragraph("Liste de paiement aux formateur :",Header3));
 document.add(new Paragraph("                                                                                                    "));
/////////liste de paiement formateur///////////////////////////////
 PdfPTable Table2 = new PdfPTable(3);

      Table2.setWidthPercentage(70f);

      Table2.setWidths(new int []{35,30,35});
 Table2.addCell("Formateur: ");
 Table2.addCell("Montant:");
    Table2.addCell("effectue le:");

PreparedStatement pstmt2 = conn.prepareStatement("select * from paiement_formateur where date <'"+d2+"' and date >'"+d1+"' ");

          rs2 = pstmt2.executeQuery();
int cin=0;
int total=0;
          while(rs2.next())
          {

int mont=rs2.getInt("montant");
int f=rs2.getInt("cin_formateur");
Date D=rs2.getDate("date");
total=total+mont;
cin=f;
PreparedStatement pstmt3 = conn.prepareStatement("select * from formateur where cin_formateur='"+cin+"'");
          rs3 = pstmt3.executeQuery();
          while(rs3.next())
          {
              String nom=rs3.getString("nom");
              String prenom=rs3.getString("prenom");
               Table2.addCell(""+nom+" "+prenom+"") ;
               Table2.addCell(Integer.toString(mont)) ;
 Table2.addCell(D.toString());
          }
 
          }
Table2.addCell("");
Table2.addCell("");
Table2.addCell("");
Table2.addCell("");
Table2.addCell("total");
Table2.addCell(Integer.toString(total)) ;

          document.add(Table2);
document.add(new Paragraph("Recette du formation :",Header3));
 document.add(new Paragraph("                                                                                                    "));
 //////Recette formation ///////////////////
PdfPTable Table4 = new PdfPTable(3);

      Table4.setWidthPercentage(70f);

      Table4.setWidths(new int []{35,30,35});
 Table4.addCell("Etudiant: ");
 Table4.addCell("Montant:");
    Table4.addCell("effectue le:");

PreparedStatement pstmt5 = conn.prepareStatement("select * from inscription where date_inscription <'"+d2+"' and date_inscription >'"+d1+"' ");

          rs2 = pstmt5.executeQuery();
int cinet=0 ,totp=0 ;
          while(rs2.next())
          {

int mont=rs2.getInt("montant_payer");
int f=rs2.getInt("cin_etudiant");
Date D=rs2.getDate("date_inscription");
totp=totp+mont;
cinet=f;
PreparedStatement pstmt6 = conn.prepareStatement("select * from etudiant where cin_etudiant='"+cinet+"'");
          rs3 = pstmt6.executeQuery();
          while(rs3.next())
          {
              String nom=rs3.getString("nom");
              String prenom=rs3.getString("prenom");
               Table4.addCell(""+nom+" "+prenom+"") ;
               Table4.addCell(Integer.toString(mont)) ;
 Table4.addCell(D.toString());
          }
 
          }
Table4.addCell("") ;
Table4.addCell("") ;
               Table4.addCell("") ;
Table4.addCell("") ;
Table4.addCell("total") ;
               Table4.addCell(Integer.toString(totp)) ;
          document.add(Table4);
////////////////Recette encadrement//////////
document.add(new Paragraph("Recette d'encadrement :",Header3));
 document.add(new Paragraph("                                                                                                    "));
PdfPTable Table3 = new PdfPTable(3);

      Table3.setWidthPercentage(70f);

      Table3.setWidths(new int []{35,30,35});
 Table3.addCell("Etudiant: ");
 Table3.addCell("Montant:");
    Table3.addCell("effectue le:");

PreparedStatement pstmt4 = conn.prepareStatement("select * from seance_encadrement where date <'"+d2+"' and date >'"+d1+"' ");

          rs2 = pstmt4.executeQuery();
int cine=0 , tote=0;
          while(rs2.next())
          {
int ph=rs2.getInt("prix_heure");
int nbh=rs2.getInt("nb_heures");
int mont=ph*nbh;
tote=tote+mont;
int f=rs2.getInt("cin_etudiant");
Date D=rs2.getDate("date");
cine=f;
PreparedStatement pstmt3 = conn.prepareStatement("select * from etudiant where cin_etudiant='"+cine+"'");
          rs3 = pstmt3.executeQuery();
          while(rs3.next())
          {
              String nom=rs3.getString("nom");
              String prenom=rs3.getString("prenom");
               Table3.addCell(""+nom+" "+prenom+"") ;
               Table3.addCell(Integer.toString(mont)) ;
 Table3.addCell(D.toString());
          }
 
          }
Table3.addCell("") ;
Table3.addCell("") ; Table3.addCell("") ; Table3.addCell("") ;
               Table3.addCell("total") ;
               Table3.addCell(Integer.toString(tote)) ;
          document.add(Table3);
 document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("Centre de la formation professionnel                                           Signature Directrice "));
document.add(new Paragraph("Avenue 14 Janvier Rue Ahmed Aloulou                                                                 "));
document.add(new Paragraph("Imm. Ragheb étage. 2 App. 4 -Sfax                                                                                                   "));
document.close();

imprime();

      }catch(Exception e)
      {
      System.out.println(e.getMessage());
      }
                }

    }//GEN-LAST:event_jButton1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recape().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
