/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tache.java
 *
 * Created on 19 avr. 2014, 22:53:35
 */

package graphique;
import java.sql.*;

import net.proteanit.sql.DbUtils ;
import javax.swing.* ;
import java.awt.* ;

/**
 *
 * @author zied_2
 */
public class tache extends javax.swing.JFrame {
    ResultSet rs;
    
Connection conn=connexion_bd.connexion();
    /** Creates new form tache */
    public tache() {
        initComponents();
     ajout_tache();
        
        modifier_tache();
        update_tache();
        annule();
        this.setTitle("Formateur");
         conn=connexion_bd.connexion();
    }
    private void update_tache(){
     try{
	      

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from tache  ");

          rs = pstmt1.executeQuery();

tache_table.setModel(DbUtils.resultSetToTableModel(rs));

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
    }
    private void annule()
            //code pour vider les champ
    {
tache.setText("");
date.setDate(null);
heure.setText("");
nbheures.setText("");
    }
    private void ajout_tache()
            // code ajout formateur
    {
 try{
	  
	    		PreparedStatement pstmt1 = conn.prepareStatement("insert into tache(tache,date,heure,nb_heures) values (?,?,?,?)");



 pstmt1.setString(1,tache.getText());
  pstmt1.setString(2,((JTextField)date.getDateEditor().getUiComponent()).getText());
    pstmt1.setString(3,heure.getText());
    pstmt1.setInt(4,Integer.parseInt(nbheures.getText()));


         int resultat = pstmt1.executeUpdate();



	    		 JOptionPane.showMessageDialog(null,"formateur enregistrer");
	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
         update_tache ();
    }
    
     private void modifier_tache()
             //code pour modifier un formateur
     {

try{
              int row=tache_table.getSelectedRow();
 String ID=(tache_table.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);

String tach=tache.getText();
 String dt = ((JTextField)date.getDateEditor().getUiComponent()).getText();
 String heur=heure.getText();
 int nbh=Integer.parseInt(nbheures.getText());




        PreparedStatement pstmt1 = conn.prepareStatement("update  tache set tache='"+tach+"' , date='"+dt+"' , heure='"+heur+"', nb_heures='"+nbh+"' where id_tache= '"+id+"' ");




         int resultat = pstmt1.executeUpdate();


	    		 JOptionPane.showMessageDialog(null,"mise à jour effectuer");
          tache.setText("");
          date.setDate(null);
          heure.setText("");
          nbheures.setText("");



	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
         update_tache ();




     }
     
             //mise à jour de jtable contenu
     
    
     


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tache_table = new javax.swing.JTable();
        tache = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        heure = new javax.swing.JTextField();
        nbheures = new javax.swing.JTextField();
        ajout = new javax.swing.JButton();
        annule = new javax.swing.JButton();
        modif = new javax.swing.JButton();
        supprime = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        deconnex = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        panel1.setLayout(null);

        tache_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tache_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tache_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tache_table);

        panel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 70, 550, 240);
        panel1.add(tache);
        tache.setBounds(760, 80, 160, 40);

        date.setDateFormatString("yyyy-MM-dd");
        panel1.add(date);
        date.setBounds(760, 150, 160, 40);
        panel1.add(heure);
        heure.setBounds(760, 210, 160, 40);
        panel1.add(nbheures);
        nbheures.setBounds(760, 270, 160, 40);

        ajout.setBackground(new java.awt.Color(0, 204, 204));
        ajout.setForeground(new java.awt.Color(255, 255, 255));
        ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ajouter-crayon-icone-4828-32.png"))); // NOI18N
        ajout.setText("ajouter");
        ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutMouseClicked(evt);
            }
        });
        panel1.add(ajout);
        ajout.setBounds(760, 340, 160, 50);

        annule.setBackground(new java.awt.Color(0, 204, 204));
        annule.setForeground(new java.awt.Color(255, 255, 255));
        annule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-7248-32.png"))); // NOI18N
        annule.setText("annuler");
        annule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annuleMouseClicked(evt);
            }
        });
        panel1.add(annule);
        annule.setBounds(590, 340, 160, 50);

        modif.setBackground(new java.awt.Color(0, 204, 204));
        modif.setForeground(new java.awt.Color(255, 255, 255));
        modif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/kedit-icone-8843-32.png"))); // NOI18N
        modif.setText("modifier");
        modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifMouseClicked(evt);
            }
        });
        panel1.add(modif);
        modif.setBounds(400, 340, 160, 50);

        supprime.setBackground(new java.awt.Color(0, 204, 204));
        supprime.setForeground(new java.awt.Color(255, 255, 255));
        supprime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-4878-32.png"))); // NOI18N
        supprime.setText("supprimer");
        supprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimeMouseClicked(evt);
            }
        });
        panel1.add(supprime);
        supprime.setBounds(200, 340, 160, 50);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boutton/accueil.jpg"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        panel1.add(jButton6);
        jButton6.setBounds(30, 70, 150, 150);

        deconnex.setBackground(new java.awt.Color(102, 0, 51));
        deconnex.setForeground(new java.awt.Color(255, 255, 255));
        deconnex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/deconnexion.jpg"))); // NOI18N
        deconnex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deconnexMouseClicked(evt);
            }
        });
        deconnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexActionPerformed(evt);
            }
        });
        panel1.add(deconnex);
        deconnex.setBounds(30, 240, 150, 150);

        getContentPane().add(panel1);
        panel1.setBounds(30, 70, 960, 490);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logooo copie.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1190, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMouseClicked
        // TODO add your handling code here:
        ajout_tache();
    }//GEN-LAST:event_ajoutMouseClicked

    private void supprimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimeMouseClicked
        // TODO add your handling code here:
         int row=tache_table.getSelectedRow();
         if (row>0)
          
         {       int c=JOptionPane.showConfirmDialog(null,"tu veux supprimer"," supprime",JOptionPane.YES_NO_OPTION);

        if(c==0){

try{

          
           String ID=(tache_table.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);
	      Class.forName("com.mysql.jdbc.Driver");
	      String dbUrl = "jdbc:mysql://localhost:3306/gesfor";

	    		PreparedStatement pstmt1 = conn.prepareStatement("delete  from tache where id_tache= '"+id+"' ");

         int resultat= pstmt1.executeUpdate();

JOptionPane.showMessageDialog(null,"mise à jour éffectuer avec succes");

}


	    	catch(Exception e){
	    		System.out.println(e.getMessage());

	    	}
         update_tache();
         }}
         else{JOptionPane.showMessageDialog(null,"aucun ligne sélectionnée");}

    }//GEN-LAST:event_supprimeMouseClicked

    private void modifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifMouseClicked
        // TODO add your handling code here:
        modifier_tache();
    }//GEN-LAST:event_modifMouseClicked

    private void annuleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_annuleMouseClicked
        // TODO add your handling code here:
        annule();
    }//GEN-LAST:event_annuleMouseClicked

    private void tache_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tache_tableMouseClicked
        // TODO add your handling code here:
         try{

           int row=tache_table.getSelectedRow();
           String ID=(tache_table.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from tache where id_tache= '"+id+"' ");

          rs = pstmt1.executeQuery();

if (rs.next())
{



String tach=rs.getString("tache");
tache.setText(tach);
Date dat=rs.getDate("date");
date.setDate(dat);
String heur=rs.getString("heure");
heure.setText(heur);
int nbh=rs.getInt("nb_heures");
nbheures.setText(Integer.toString(nbh));



}

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}

    }//GEN-LAST:event_tache_tableMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        accueil  appelfenetre=new  accueil();
        appelfenetre.setExtendedState(appelfenetre.MAXIMIZED_BOTH);
        appelfenetre.setVisible(true) ;

        this.setVisible(false);
}//GEN-LAST:event_jButton6MouseClicked

    private void deconnexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnexMouseClicked
        // TODO add your handling code here:
        connexion  appelfenetre=new  connexion();
        appelfenetre.setExtendedState(appelfenetre.MAXIMIZED_BOTH);
        appelfenetre.setVisible(true) ;

        this.setVisible(false);
}//GEN-LAST:event_deconnexMouseClicked

    private void deconnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_deconnexActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tache().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajout;
    private javax.swing.JButton annule;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton deconnex;
    private javax.swing.JTextField heure;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modif;
    private javax.swing.JTextField nbheures;
    private java.awt.Panel panel1;
    private javax.swing.JButton supprime;
    private javax.swing.JTextField tache;
    private javax.swing.JTable tache_table;
    // End of variables declaration//GEN-END:variables

}
