/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * testevaluation.java
 *
 * Created on 23 avr. 2014, 20:50:07
 */

package graphique;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils ;


/**
 *
 * @author zied_2
 */
public class testevaluation extends javax.swing.JFrame {
ResultSet rs , rs2,rs3;
    Connection conn=connexion_bd.connexion();

    /** Creates new form testevaluation */
    public testevaluation() throws IOException {
        initComponents();
        conn=connexion_bd.connexion();
        update_etudiant();
        matiere();
        update_test();
        this.setTitle("Gestionnaire de tests");
        
    }
    private void imprime () throws IOException
    {
        try
        {
    Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\zied_2\\Documents\\NetBeansProjects\\Gesfor\\dist\\buelltin.pdf");
        }
    catch(Exception e)
    {
      System.out.println(e.getMessage());
    }
    }
    private void update_test()
    {
        try{

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from test_evaluation ");

          rs = pstmt1.executeQuery();

test.setModel(DbUtils.resultSetToTableModel(rs));

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
    }
      private void update_etudiant() {
          try{

	    		PreparedStatement pstmt1 = conn.prepareStatement("select cin_etudiant from etudiant");

          rs = pstmt1.executeQuery();

while(rs.next())
{
    int cine=rs.getInt("cin_etudiant");
    etudiant.addItem(Integer.toString(cine));
    
}

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}

    }

       private void matiere()
  {
 try{

	    		PreparedStatement pstmt1 = conn.prepareStatement("select nom_matiere from matiere");

          rs = pstmt1.executeQuery();

while(rs.next())
{
    String cinf=rs.getString("nom_matiere");
    matiere.addItem(cinf);
}

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ajout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        test = new javax.swing.JTable();
        matiere = new javax.swing.JComboBox();
        etudiant = new javax.swing.JComboBox();
        date = new com.toedter.calendar.JDateChooser();
        note = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        panel1.setLayout(null);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/icon_print.png"))); // NOI18N
        jButton4.setText("generer buelltin");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        panel1.add(jButton4);
        jButton4.setBounds(190, 490, 170, 40);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/supprimer-icone-7248-32.png"))); // NOI18N
        jButton3.setText("Annuler");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        panel1.add(jButton3);
        jButton3.setBounds(370, 440, 150, 40);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/kedit-icone-8843-32.png"))); // NOI18N
        jButton2.setText("Modifier Test");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        panel1.add(jButton2);
        jButton2.setBounds(190, 440, 170, 40);

        ajout.setBackground(new java.awt.Color(204, 204, 255));
        ajout.setForeground(new java.awt.Color(255, 255, 255));
        ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ajouter-crayon-icone-4828-32.png"))); // NOI18N
        ajout.setText("Enregistrer Test");
        ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutMouseClicked(evt);
            }
        });
        panel1.add(ajout);
        ajout.setBounds(10, 440, 160, 40);

        test.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(test);

        panel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 510, 310);

        panel1.add(matiere);
        matiere.setBounds(550, 220, 210, 40);

        panel1.add(etudiant);
        etudiant.setBounds(550, 140, 210, 40);

        date.setDateFormatString("yyyy-MM-dd");
        panel1.add(date);
        date.setBounds(550, 390, 210, 40);

        note.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noteMouseClicked(evt);
            }
        });
        note.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noteKeyTyped(evt);
            }
        });
        panel1.add(note);
        note.setBounds(550, 300, 210, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Gestionnaire De Tests D'étudiants ");
        panel1.add(jLabel2);
        jLabel2.setBounds(210, 10, 370, 40);

        jTextField1.setText("Id_formation");
        panel1.add(jTextField1);
        jTextField1.setBounds(10, 490, 160, 40);

        jLabel3.setText("Cin étudiant:");
        panel1.add(jLabel3);
        jLabel3.setBounds(550, 114, 140, 20);

        jLabel4.setText("Matière:");
        panel1.add(jLabel4);
        jLabel4.setBounds(550, 194, 140, 20);

        jLabel5.setText("Note:");
        panel1.add(jLabel5);
        jLabel5.setBounds(550, 274, 110, 20);

        jLabel6.setText("Date de test:");
        panel1.add(jLabel6);
        jLabel6.setBounds(550, 360, 120, 14);

        getContentPane().add(panel1);
        panel1.setBounds(100, 50, 840, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/logooo copie.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1400, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMouseClicked
        // TODO add your handling code here:
        int etudiantt=Integer.parseInt(etudiant.getSelectedItem().toString());
        String matier=matiere.getSelectedItem().toString();
        float not=Float.parseFloat(note.getText());
        String dt=((JTextField)date.getDateEditor().getUiComponent()).getText();
        try
        {
          PreparedStatement pstmt1=conn.prepareStatement("insert into test_evaluation (cin_etudiant,matiere,note,date) values (?,?,?,?)");
          pstmt1.setInt(1,etudiantt);
      pstmt1.setString(2,matier);
      pstmt1.setFloat(3,not);
      pstmt1.setString(4,dt);
      int resultat=pstmt1.executeUpdate();

      JOptionPane.showMessageDialog(null,"test enregistrer");
        }
        catch(Exception e)
        {
JOptionPane.showMessageDialog(null,"e");
        }
        update_test();
    }//GEN-LAST:event_ajoutMouseClicked

    private void testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testMouseClicked
        // TODO add your handling code here:
         try{

           int row=test.getSelectedRow();
           String ID=(test.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);

	    		PreparedStatement pstmt1 = conn.prepareStatement("select * from test_evaluation where id_test= '"+id+"' ");

          rs = pstmt1.executeQuery();


while (rs.next())
{

int cine=rs.getInt("cin_etudiant") ;
String matier=rs.getString("matiere");
Date dt=rs.getDate("date");
date.setDate(dt);

float not=rs.getFloat("note");

note.setText(Float.toString(not));

}

	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}

    }//GEN-LAST:event_testMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        note.setText("");
        date.setDate(null);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         try{

           int row=test.getSelectedRow();
           String ID=(test.getModel().getValueAt(row, 0).toString());
           int id ;
           id=Integer.parseInt(ID);
String matier=matiere.getSelectedItem().toString();
int etud=Integer.parseInt(etudiant.getSelectedItem().toString());
float not=Float.parseFloat(note.getText());
String dt=((JTextField)date.getDateEditor().getUiComponent()).getText();

        PreparedStatement pstmt1 = conn.prepareStatement("update  test_evaluation set cin_etudiant='"+etud+"' , matiere='"+matier+"',note='"+not+"',date='"+dt+"' where id_test= '"+id+"' ");




         int resultat = pstmt1.executeUpdate();


	    		 JOptionPane.showMessageDialog(null,"mise à jour effectuer");




	    }
	    	catch(Exception c){
	    		System.out.println(c.getMessage());

	    	}
         update_test();

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
         Font Header3 =FontFactory.getFont("Arial",BaseFont.IDENTITY_H,9,Font.NORMAL);
     Document document = new Document();
     String NomFichierPDF = "buelltin.pdf";

            try
      {
      PdfWriter.getInstance(document,new FileOutputStream(NomFichierPDF)).setInitialLeading(13f);
      document.open();
      Calendar cal=new GregorianCalendar() ;
      int Y=cal.get(Calendar.YEAR);
  int M=cal.get(Calendar.MONTH);
  int d=cal.get(Calendar.DAY_OF_MONTH);
  String datecurrent=Y+"-"+(M+1)+"-"+d ;
Image image=Image.getInstance("log.jpg");
      document.add(image);
      document.add(new Paragraph("                                                                                                    "));
      document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                 Bulletin de note"));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                     "+datecurrent+"                "));
document.add(new Paragraph("                                                                        "));

      PdfPTable Table = new PdfPTable(4);
      int row=test.getSelectedRow();
      int cin=Integer.parseInt(test.getModel().getValueAt(row, 1).toString());
 PreparedStatement pstmt2 = conn.prepareStatement("select * from etudiant where cin_etudiant='"+cin+"' ");
 rs3=pstmt2.executeQuery();
 String ne="", pe="" ;
 while(rs3.next()){
     ne=rs3.getString("nom");
     pe=rs3.getString("prenom");
 }
      Table.setWidthPercentage(70f);
      Table.addCell("nom:");

      Table.addCell(ne);

      Table.addCell("prénom:");

      Table.addCell(pe);
      Table.addCell("cin:");

      Table.addCell(Integer.toString(cin));

Table.addCell("");
Table.addCell("");
       Table.addCell("matière");

      Table.addCell("coeffécient");

      Table.addCell("note");

      Table.addCell("total");

           String matier=(test.getModel().getValueAt(row, 2).toString());
            
          PreparedStatement pstmt1 = conn.prepareStatement("select * from test_evaluation where cin_etudiant='"+cin+"' ");
         
      rs=pstmt1.executeQuery();
      float moyen=0;
      float total=0;
      float totaln=0;
      int totalc=0;
      while(rs.next())
      {
          int coefec=0;
          
          String mat=rs.getString("matiere");
          float not=rs.getFloat("note");
          PreparedStatement pstmt4 = conn.prepareStatement("select * from heures_enseignee where matiere='"+mat+"' ");
          rs2=pstmt4.executeQuery();
          while (rs2.next())
          {
          int coef=rs2.getInt("coeffecient");
          coefec=coef;
          totalc=totalc+coefec;
          total=coefec*not;
          totaln=totaln+total;
          }
 moyen=(totaln/totalc);
           Table.addCell(mat);

      Table.addCell(Integer.toString(coefec));

      Table.addCell(Float.toString(not));

      Table.addCell(Float.toString(total));
      }

      Table.addCell("");

      Table.addCell("");
      Table.addCell("total");

      Table.addCell(Float.toString(totaln));
      Table.addCell("");

      Table.addCell("");
       Table.addCell("moyen");

      Table.addCell(Float.toString(moyen));

    	

  document.add(Table);

document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("                                                                                                    "));
document.add(new Paragraph("Centre de la formation professionnel                                           Signature Directrice "));
document.add(new Paragraph("Avenue 14 Janvier Rue Ahmed Aloulou                                                                 "));
document.add(new Paragraph("Imm. Ragheb étage. 2 App. 4 -Sfax                                                                                                   "));

document.close();

imprime();
      }catch(Exception e)
      {
      System.out.println(e.getMessage());
      }


    }//GEN-LAST:event_jButton4MouseClicked

    private void noteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noteMouseClicked
        // TODO add your handling code here:
        note.setText("");
    }//GEN-LAST:event_noteMouseClicked

    private void noteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noteKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if((Character.isAlphabetic(c) )|| ( c==KeyEvent.VK_SPACE  ))
        {
          JOptionPane.showMessageDialog(null,"type non valide");
        }
    }//GEN-LAST:event_noteKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new testevaluation().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(testevaluation.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajout;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JComboBox etudiant;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox matiere;
    private javax.swing.JTextField note;
    private java.awt.Panel panel1;
    private javax.swing.JTable test;
    // End of variables declaration//GEN-END:variables

}
